version: '3.0'

services:
    json_server:
        image: node:latest
        working_dir: /json_server
        volumes:
        - ./json_server_files:/json_server
        command: bash src.sh
        expose:
        - 8000

    lite_server:
        image: node:latest
        working_dir: /lite_server
        volumes:
        - ./lite_server_files:/lite_server
        command: bash src.sh
        expose:
        - 3000

    nginx:
        image: nginx
        volumes:
        - ./nginx_templates:/etc/nginx/templates
        ports:
        - "8080:80"
        links:
        - json_server
        - lite_server